## Basics of Numpy
Author: W.P

#### Defining a simple array in Numpy

- Also known as vectors (collection of scalar values)

In [1]:
import numpy as np

In [2]:
# Defining a simple array - 1 dimentional
my_array = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
print(my_array)

[1 2 3 4 5 6 7 8 9]


#### Addition  

The example defines two vectors with five elements each, then adds them together.
- must be of the same length 
- preferably of the same data types 



In [4]:
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
c = a + b
print(c)


[11 12 13 14 15]


#### Subtraction  

The example defines two vectors with five elements each, then subtract the second one from the first one.
- must be of the same length 
- preferably of the same data types 

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
c = b - a
print(c)

[9 8 7 6 5]


#### Multiplication  

The example defines two vectors with five elements each, then multiply them.
- must be of the same length 
- preferably of the same data types 

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
c = a * b
print(c)

[10 20 30 40 50]


#### Division  

The example defines two vectors with five elements each, then divide the first one with the second one.
- must be of the same length 
- mind the type change


In [7]:
a = np.array([10,20,30,40,50])
b = np.array([10,10,10,10,10])

c = a / b
print(c)
print(type(c))
print(a.dtype)
print(b.dtype)
print(c.dtype)  # changed to float!

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
int32
int32
float64


#### Vector Dot Product

We can calculate the sum of the multiplied elements of two vectors of the same length. The result would be a scalar.

In the following example, we take the first vector and multiply it to the corresponding element (same index) of the second array and then sum them up.

That is 

a . b = (1 x 10) + (2 x 5) + (4 x 2)  
a . b = 10 + 10 + 8
The final product
a . b = 28 

In [8]:
a = np.array([1,2,4])
b = np.array([10,5,2])
c = a.dot(b)
print(c)

28


#### Vector-Scalar multiplication/addition/subtraction/division

- Vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. 
- The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.
- Similarly, vector-scalar addition, subtraction, and division can be performed in the same way.

 


In [9]:
a = np.array([10,20,30,40,50])
b = a * 5 
c = a + 5 
d = a - 5 
e = a / 5 
print("a * 5 = ",b)
print("a + 5 = ",c)
print("a - 5 = ",d)
print("a / 5 = ",e) # mind the data type change



a * 5 =  [ 50 100 150 200 250]
a + 5 =  [15 25 35 45 55]
a - 5 =  [ 5 15 25 35 45]
a / 5 =  [ 2.  4.  6.  8. 10.]
