## Basics of Numpy
Author: W.P

#### Defining a simple array in Numpy 

- Also known as vectors (collection of scalar values)

In [1]:
import numpy as np

In [2]:
# Defining a simple array - 1 dimentional
my_array = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
print(my_array)

[1 2 3 4 5 6 7 8 9]


#### Addition  

The example defines two vectors with five elements each, then adds them together.
- must be of the same length 
- preferably of the same data types 



In [4]:
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
c = a + b
print(c)

[11 12 13 14 15]


#### Subtraction  

The example defines two vectors with five elements each, then subtract the second one from the first one.
- must be of the same length 
- preferably of the same data types 

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
c = b - a
print(c)

[9 8 7 6 5]


#### Multiplication  

The example defines two vectors with five elements each, then multiply them.
- must be of the same length 
- preferably of the same data types 

In [6]:
# Vector x Vector 
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
c = a * b
print(c)



[10 20 30 40 50]


#### Division  

The example defines two vectors with five elements each, then divide the first one with the second one.
- must be of the same length 
- mind the type change


In [7]:
a = np.array([10,20,30,40,50])
b = np.array([10,10,10,10,10])

c = a / b
print(c)
print(type(c))
print(a.dtype)
print(b.dtype)
print(c.dtype)  # changed to float!

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
int32
int32
float64


#### Vector Dot Product

We can calculate the sum of the multiplied elements of two vectors of the same length. The result would be a scalar.

In the following example, we take the first vector and multiply it to the corresponding element (same index) of the second array and then sum them up.

That is 

a . b = (1 x 10) + (2 x 5) + (4 x 2)  
a . b = 10 + 10 + 8
The final product
a . b = 28 

In [8]:
a = np.array([1,2,4])
b = np.array([10,5,2])
c = a.dot(b)
print(c)

28


#### Vector-Scalar multiplication/addition/subtraction/division

- Vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. 
- The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.
- Similarly, vector-scalar addition, subtraction, and division can be performed in the same way.

 


In [9]:
a = np.array([10,20,30,40,50])
b = a * 5 
c = a + 5 
d = a - 5 
e = a / 5 
print("a * 5 = ",b)
print("a + 5 = ",c)
print("a - 5 = ",d)
print("a / 5 = ",e) # mind the data type change



a * 5 =  [ 50 100 150 200 250]
a + 5 =  [15 25 35 45 55]
a - 5 =  [ 5 15 25 35 45]
a / 5 =  [ 2.  4.  6.  8. 10.]


#### 1D-Array (Vector) initialization with __arange__  and Data Retrieval (slicing and boolean indexing)

In [10]:
a = np.arange(0,10,1)
print(a)
# Slicing
print(a[0:2])  # the first two 
print(a[-2:])  # the last two

# Boolean Indexing
print(np.any(a > 5)) # check to see if any value exist that is greater than 5 and if yes, return True, otherwise False
print(np.all(a>5)) # check to see if all values of a are greater than 5 and if yes, return True, otherwise False
print(a[a>5]) # return any item that is bigger than 5


[0 1 2 3 4 5 6 7 8 9]
[0 1]
[8 9]
True
False
[6 7 8 9]


#### 2D-Array (Matrix) initialization 

In [11]:
my_2d_array_1 = np.array([[1,2,3],[4,5,6]])

In [12]:
print(my_2d_array_1)
print("shape of the array is :" , my_2d_array_1.shape)

[[1 2 3]
 [4 5 6]]
shape of the array is : (2, 3)


In [13]:
my_2d_array_2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(my_2d_array_2)
print("shape of the array is : ", my_2d_array_2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape of the array is :  (3, 4)


#### 2D-Array Indexing

In [14]:
print(my_2d_array_2[0,0:4])  # Row 1 , all columns

[1 2 3 4]


In [15]:
print(my_2d_array_2[1,0:4])  # Row 2 , all columns

[5 6 7 8]


In [16]:
print(my_2d_array_2[0,1:3])  # Row 1 , two middle columns

[2 3]


In [17]:
print(my_2d_array_2[0:3,3])  # Row 1 to 3 , last column

[ 4  8 12]


In [18]:
print(my_2d_array_2[0:3,0:2])  # Row 1 to 3 , first two column

[[ 1  2]
 [ 5  6]
 [ 9 10]]


#### 2D-Arrays and Axes 

In [19]:
my_2d_array_3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(my_2d_array_3)
print("The sum across vertical axis (axis = 0) is : ",np.sum(my_2d_array_3, axis = 0)) # sums down the columns
print("The sum across horizontal axis (axis = 1) is : ",np.sum(my_2d_array_3, axis = 1)) # sums down the columns

[[0 1 2]
 [3 4 5]
 [6 7 8]]
The sum across vertical axis (axis = 0) is :  [ 9 12 15]
The sum across horizontal axis (axis = 1) is :  [ 3 12 21]


![alt text](images\axis.png "Title")

#### Numpy Concatenate 

When we use the axis parameter with the np.concatenate() function, the axis parameter defines the axis along which we stack the arrays.

In [20]:
np_array_2s = np.array ([[2,2,2],[2,2,2]])
np_array_8s = np.array ([[8,8,8],[8,8,8]])
print(np_array_2s)
print(np_array_2s.shape)
print(np_array_8s)
print(np_array_8s.shape)

[[2 2 2]
 [2 2 2]]
(2, 3)
[[8 8 8]
 [8 8 8]]
(2, 3)


##### Numpy Concatenate - Axis = 0 

In [21]:
result = np.concatenate([np_array_2s,np_array_8s],axis = 0)
print(result)
print(result.shape)
# axis = 0 will stack the arrays vertically
# first array shape is (2,3) and the second array shape is (2,3), the result of concatination will have shape of (4,3)

[[2 2 2]
 [2 2 2]
 [8 8 8]
 [8 8 8]]
(4, 3)


##### Numpy Concatenate - Axis = 1

In [22]:
result = np.concatenate([np_array_2s,np_array_8s],axis = 1)
print(result)
print(result.shape)
# axis = 1 will stack the arrays horizontally
# first array shape is (2,3) and the second array shape is (2,3), the result of concatination will have shape of (2,6)

[[2 2 2 8 8 8]
 [2 2 2 8 8 8]]
(2, 6)


#### 3D-Arrays
When you create a 3D array, the indices are (z,y,x). The first index is the number of the plane, then the coordinates go in that plane.
![alt text](images/3d-simple-array.png "Title")

In [23]:
np_array_3d_1 = np.arange(1,9).reshape(2,2,2)
print(np_array_3d_1)
print("Number of dimentions: ", np_array_3d_1.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Number of dimentions:  3


##### Accessing items in a 3D array
![alt text](images/3d-array.png "Title")


In [24]:
np_array_3d_2 = np.array ([[[0,0,0,0],[0,0,0,0]],[[1,1,1,1],[1,1,1,1]],[[2,2,2,2],[2,2,2,2]]])

In [25]:
print(np_array_3d_2)
print(np_array_3d_2.shape)
print("Number of dimentions: ", np_array_3d_2.ndim)

[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]]]
(3, 2, 4)
Number of dimentions:  3


##### Example of accessing items in 3D arrays

In [26]:
np_array_3d_3= np.array ([[[10,20,30,40],[40,50,60,70]],[[15,25,35,45],[55,65,75,85]],[[100,200,300,400],[500,600,700,800]]])

      

Accessing various items in the above array


In [27]:
print(np_array_3d_3[0,1,2]) # First matrix , second row, third item

60


In [28]:
print(np_array_3d_3[2,1,3]) #  Third matrix , second row, forth item

800
